language: node_js
node_js:
- lts/*
cache:
  yarn: true
branches:
  only:
  - master
  - develop
script:
- yarn test
- yarn build
deploy:
  provider: npm
  email: me@neoto.xin
  api_key:
    secure: sXDVKgClD4bBre3F1nKJo8DRw48Wol/MfaYNNm9xnMwn283neaNgXBb1JwLTsPyQn0+n5cStTr271VNfHTAwSUWzTR10o/uLuNc4a88MzIb1aEBWOu3woNkHmDl4U7LZaQa/cgw1CP5QeA7JISUxzULh4D0MvEzMxclNgG9zL8FiIX8R7N1Dc7i6ScZtoF00OqTaVHBKaYhjYWmdKpq79CmEzggNqalRv9bhIG8h78OZq2Wtjm7ZKzm5srhTn/BQI3xBwS8ADI2CF/vn3xFl59xFwnHvPXvt8es87oTJ2BCowbwsZBH3RUXSlRiaW9bZuvTWq/tZVkGtr9Fm7idGfrN1zxu4ZtVd+mz5lNCcf1qx/pQv3VtOp4h26dNIYiDQfKLXRsF7M8O5CZTzlAeP+kdRbv/7CE9cTGco5KkbKNA2s9KoSGAshUotJQk8Pt7IP/yzM/mIJ/9UAfHjVD1MFsiNN9tFFxBAW4UyaThavkocACnOhGRiB3D5NUISsnZR2LzGPS8FoCEex7WwSQTjoDaI9/xvOWveiskow+Dy5UEYlAlPxI63hWxxb0lFDYYCAayTegW5uxlkfK2+ihKOXEE5mq/nQ4YU+6X/1f6omRifi7CxGvWWNrk7aFnBkK2bC83robq6iFThd6dgEYIyoO1urGCl/U8ZA9LQdMwD/FM=
